/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package sarisaristoreinventoryandsalesmanagementsytem;

/**
 *
 * @author Helia Pearl Charish
 */
public class DashboardInternalFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form DashboardInternalFrame
     */
    public DashboardInternalFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDashboard = new javax.swing.JPanel();
        lblDashboardTitle = new javax.swing.JLabel();
        lblDashboardDescription = new javax.swing.JLabel();
        btnDashboardAddProduct = new javax.swing.JButton();
        btnDashboardRestock = new javax.swing.JButton();
        btnDashboardDailyGain = new javax.swing.JButton();
        btnDashboardPuhunan = new javax.swing.JButton();
        btnDashboardInventory = new javax.swing.JButton();
        btnDashboardCashier = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setTitle("Dashboard");
        setPreferredSize(new java.awt.Dimension(1570, 960));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlDashboard.setBackground(new java.awt.Color(255, 255, 255));

        lblDashboardTitle.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        lblDashboardTitle.setForeground(new java.awt.Color(0, 51, 255));
        lblDashboardTitle.setText("Dashboard");

        lblDashboardDescription.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblDashboardDescription.setForeground(new java.awt.Color(102, 102, 102));
        lblDashboardDescription.setText("Manage your store efficiently.");

        btnDashboardAddProduct.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnDashboardAddProduct.setForeground(new java.awt.Color(0, 51, 255));
        btnDashboardAddProduct.setIcon(new javax.swing.ImageIcon("C:\\Users\\Helia Pearl Charish\\Downloads\\add-plus-5834_64 (1).png")); // NOI18N
        btnDashboardAddProduct.setText("Add Product");
        btnDashboardAddProduct.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDashboardAddProduct.setIconTextGap(10);
        btnDashboardAddProduct.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        btnDashboardRestock.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnDashboardRestock.setForeground(new java.awt.Color(0, 51, 255));
        btnDashboardRestock.setIcon(new javax.swing.ImageIcon("C:\\Users\\Helia Pearl Charish\\Downloads\\add-to-basket-5854_64 (1).png")); // NOI18N
        btnDashboardRestock.setText("Restock Product");
        btnDashboardRestock.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDashboardRestock.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDashboardRestock.addActionListener(this::btnDashboardRestockActionPerformed);

        btnDashboardDailyGain.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnDashboardDailyGain.setForeground(new java.awt.Color(0, 51, 255));
        btnDashboardDailyGain.setIcon(new javax.swing.ImageIcon("C:\\Users\\Helia Pearl Charish\\Downloads\\medical-history-healthcare-report-green-26326_64 (1).png")); // NOI18N
        btnDashboardDailyGain.setText("Daily Gain / History");
        btnDashboardDailyGain.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDashboardDailyGain.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDashboardDailyGain.addActionListener(this::btnDashboardDailyGainActionPerformed);

        btnDashboardPuhunan.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnDashboardPuhunan.setForeground(new java.awt.Color(0, 51, 255));
        btnDashboardPuhunan.setIcon(new javax.swing.ImageIcon("C:\\Users\\Helia Pearl Charish\\Downloads\\return-on-investment-dollar-28163_64 (1).png")); // NOI18N
        btnDashboardPuhunan.setText("Puhunan");
        btnDashboardPuhunan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDashboardPuhunan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        btnDashboardInventory.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnDashboardInventory.setForeground(new java.awt.Color(0, 51, 255));
        btnDashboardInventory.setIcon(new javax.swing.ImageIcon("C:\\Users\\Helia Pearl Charish\\Downloads\\gift-box-5792_64 (1).png")); // NOI18N
        btnDashboardInventory.setText("Inventory");
        btnDashboardInventory.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDashboardInventory.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        btnDashboardCashier.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnDashboardCashier.setForeground(new java.awt.Color(0, 51, 255));
        btnDashboardCashier.setIcon(new javax.swing.ImageIcon("C:\\Users\\Helia Pearl Charish\\Downloads\\wallet-5880_64.png")); // NOI18N
        btnDashboardCashier.setText("Cashier");
        btnDashboardCashier.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDashboardCashier.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout pnlDashboardLayout = new javax.swing.GroupLayout(pnlDashboard);
        pnlDashboard.setLayout(pnlDashboardLayout);
        pnlDashboardLayout.setHorizontalGroup(
            pnlDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDashboardLayout.createSequentialGroup()
                .addGroup(pnlDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDashboardLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(pnlDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDashboardDescription)
                            .addComponent(lblDashboardTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlDashboardLayout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addGroup(pnlDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDashboardPuhunan, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDashboardAddProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(155, 155, 155)
                .addGroup(pnlDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnDashboardRestock, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDashboardInventory, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 170, Short.MAX_VALUE)
                .addGroup(pnlDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDashboardDailyGain, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDashboardCashier, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(109, 109, 109))
        );
        pnlDashboardLayout.setVerticalGroup(
            pnlDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDashboardLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblDashboardTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDashboardDescription)
                .addGap(77, 77, 77)
                .addGroup(pnlDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDashboardLayout.createSequentialGroup()
                        .addComponent(btnDashboardDailyGain, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDashboardCashier, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlDashboardLayout.createSequentialGroup()
                        .addGroup(pnlDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDashboardRestock, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDashboardAddProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                        .addGroup(pnlDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnDashboardInventory, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDashboardPuhunan, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(64, 64, 64))
        );

        getContentPane().add(pnlDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDashboardDailyGainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboardDailyGainActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDashboardDailyGainActionPerformed

    private void btnDashboardRestockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboardRestockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDashboardRestockActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDashboardAddProduct;
    private javax.swing.JButton btnDashboardCashier;
    private javax.swing.JButton btnDashboardDailyGain;
    private javax.swing.JButton btnDashboardInventory;
    private javax.swing.JButton btnDashboardPuhunan;
    private javax.swing.JButton btnDashboardRestock;
    private javax.swing.JLabel lblDashboardDescription;
    private javax.swing.JLabel lblDashboardTitle;
    private javax.swing.JPanel pnlDashboard;
    // End of variables declaration//GEN-END:variables
}
