/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sarisaristoreinventoryandsalesmanagementsytem;

/**
 *
 * @author Helia Pearl Charish
 */

import java.awt.GraphicsConfiguration;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import java.awt.Rectangle;
import javax.swing.JOptionPane;
public class InventoryFrame extends javax.swing.JFrame {
    private String passedName;
    

    /**
     * Creates new form Login
     */
    public InventoryFrame(String passedName) {
        this.passedName = passedName;
        initComponents();
        
        GraphicsEnvironment ge =
            GraphicsEnvironment.getLocalGraphicsEnvironment();

        GraphicsDevice[] screens = ge.getScreenDevices();

        GraphicsDevice screen = screens[0]; // Change to screens[1] for monitor 2

        GraphicsConfiguration gc =
            screen.getDefaultConfiguration();

        Rectangle bounds = gc.getBounds();
        java.awt.Insets insets =
            java.awt.Toolkit.getDefaultToolkit().getScreenInsets(gc);

        int x = bounds.x + insets.left;
        int y = bounds.y + insets.top;

        int width = bounds.width - insets.left - insets.right;
        int height = bounds.height - insets.top - insets.bottom;
    
        setBounds(x, y, width, height);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        welcomePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        inventoryButton4 = new javax.swing.JButton();
        inventoryButton5 = new javax.swing.JButton();
        inventoryButton12 = new javax.swing.JButton();
        inventoryButton13 = new javax.swing.JButton();
        inventoryButton14 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        inventoryButton6 = new javax.swing.JButton();
        inventoryButton8 = new javax.swing.JButton();
        inventoryButton9 = new javax.swing.JButton();
        inventoryButton10 = new javax.swing.JButton();
        inventoryButton11 = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        inventoryButton7 = new javax.swing.JButton();

        welcomePanel.setBackground(new java.awt.Color(153, 153, 153));
        welcomePanel.setPreferredSize(new java.awt.Dimension(1920, 1080));
        welcomePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jLabel1.setText("Sari-Sari Store Inventory & Sales Management System");
        welcomePanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 550, 50));

        jLabel2.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N
        jLabel2.setText("Welcome!");
        welcomePanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 90, 160, 50));

        jLabel3.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jLabel3.setText("Login As:");
        welcomePanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 270, 180, 50));

        jButton2.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        jButton2.setText("Staff");
        welcomePanel.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 410, 120, 40));

        jButton3.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        jButton3.setText("Owner");
        welcomePanel.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 400, 120, 40));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 102));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 102, 255));

        jPanel3.setBackground(new java.awt.Color(51, 153, 255));

        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("SARI-SARI STORE");

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Helia Pearl Charish\\Downloads\\shopping-bag-3746_64.png")); // NOI18N
        jLabel5.setText(".");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel10.setText("View and manage your product inventory.");

        inventoryButton4.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        inventoryButton4.setText("Search");
        inventoryButton4.addActionListener(this::inventoryButton4ActionPerformed);

        inventoryButton5.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        inventoryButton5.setText("Update");
        inventoryButton5.addActionListener(this::inventoryButton5ActionPerformed);

        inventoryButton12.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        inventoryButton12.setText("+ Add Product");
        inventoryButton12.addActionListener(this::inventoryButton12ActionPerformed);

        inventoryButton13.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        inventoryButton13.setText("Delete");
        inventoryButton13.addActionListener(this::inventoryButton13ActionPerformed);

        inventoryButton14.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        inventoryButton14.setText("Restock");
        inventoryButton14.addActionListener(this::inventoryButton14ActionPerformed);

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 255));
        jLabel7.setText("Inventory");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(inventoryButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(inventoryButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(inventoryButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(inventoryButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(inventoryButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(893, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(inventoryButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(296, 296, 296)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inventoryButton5)
                    .addComponent(inventoryButton13)
                    .addComponent(inventoryButton14)
                    .addComponent(inventoryButton12))
                .addContainerGap(102, Short.MAX_VALUE))
        );

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("MANAGEMENT SYSTEM");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Barcode", "Product Name", "Category", "Original Price", "Selling Price", "Unit Cost", "Stock"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1085, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 543, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1911, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(134, 134, 134)
                    .addComponent(jLabel9)
                    .addContainerGap(1710, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel5)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(128, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(142, 142, 142))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(26, 26, 26)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(61, Short.MAX_VALUE)))
        );

        inventoryButton6.setBackground(new java.awt.Color(204, 204, 204));
        inventoryButton6.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        inventoryButton6.setText("CASHIER");
        inventoryButton6.addActionListener(this::inventoryButton6ActionPerformed);

        inventoryButton8.setBackground(new java.awt.Color(153, 153, 153));
        inventoryButton8.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        inventoryButton8.setText("INVENTORY");
        inventoryButton8.addActionListener(this::inventoryButton8ActionPerformed);

        inventoryButton9.setBackground(new java.awt.Color(204, 204, 204));
        inventoryButton9.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        inventoryButton9.setText("RESTOCK");
        inventoryButton9.addActionListener(this::inventoryButton9ActionPerformed);

        inventoryButton10.setBackground(new java.awt.Color(204, 204, 204));
        inventoryButton10.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        inventoryButton10.setText("DAILY GAIN");
        inventoryButton10.addActionListener(this::inventoryButton10ActionPerformed);

        inventoryButton11.setBackground(new java.awt.Color(204, 204, 204));
        inventoryButton11.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        inventoryButton11.setText("PUHUNAN");
        inventoryButton11.addActionListener(this::inventoryButton11ActionPerformed);

        backButton.setBackground(new java.awt.Color(153, 153, 153));
        backButton.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        backButton.setText("Back");
        backButton.addActionListener(this::backButtonActionPerformed);

        inventoryButton7.setBackground(new java.awt.Color(204, 204, 204));
        inventoryButton7.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        inventoryButton7.setText("DASHBOARD");
        inventoryButton7.addActionListener(this::inventoryButton7ActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(inventoryButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inventoryButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inventoryButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inventoryButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(inventoryButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(inventoryButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(inventoryButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(inventoryButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(inventoryButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(inventoryButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(inventoryButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(inventoryButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85)
                .addComponent(backButton)
                .addContainerGap(104, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void inventoryButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventoryButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inventoryButton6ActionPerformed

    private void inventoryButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventoryButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inventoryButton7ActionPerformed

    private void inventoryButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventoryButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inventoryButton8ActionPerformed

    private void inventoryButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventoryButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inventoryButton9ActionPerformed

    private void inventoryButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventoryButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inventoryButton10ActionPerformed

    private void inventoryButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventoryButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inventoryButton11ActionPerformed

    private void inventoryButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventoryButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inventoryButton4ActionPerformed

    private void inventoryButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventoryButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inventoryButton5ActionPerformed

    private void inventoryButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventoryButton12ActionPerformed

    }//GEN-LAST:event_inventoryButton12ActionPerformed

    private void inventoryButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventoryButton13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inventoryButton13ActionPerformed

    private void inventoryButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventoryButton14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inventoryButton14ActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        MainMenuFrame menu = new MainMenuFrame(passedName);
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backButtonActionPerformed
    // TODO add your handling code here:

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton inventoryButton10;
    private javax.swing.JButton inventoryButton11;
    private javax.swing.JButton inventoryButton12;
    private javax.swing.JButton inventoryButton13;
    private javax.swing.JButton inventoryButton14;
    private javax.swing.JButton inventoryButton4;
    private javax.swing.JButton inventoryButton5;
    private javax.swing.JButton inventoryButton6;
    private javax.swing.JButton inventoryButton7;
    private javax.swing.JButton inventoryButton8;
    private javax.swing.JButton inventoryButton9;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel welcomePanel;
    // End of variables declaration//GEN-END:variables
}
